In [41]:
#import required modules
import pandas as pd
import numpy as np

In [4]:
index = pd.date_range('1/1/2000', periods=8)
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
df = pd.DataFrame(np.random.randn(8, 3), index=index,
                      columns=['A', 'B', 'C'])

In [ ]:
 # Head and Tail

In [5]:
print(df.head())
print(df.tail())

                   A         B         C
2000-01-01  0.413298 -0.481873  0.898299
2000-01-02 -0.826705  0.880518 -0.177395
2000-01-03  0.647880  1.061217  0.457110
2000-01-04 -0.592532  1.703307 -1.031874
2000-01-05 -0.126065 -0.590199  0.031823
                   A         B         C
2000-01-04 -0.592532  1.703307 -1.031874
2000-01-05 -0.126065 -0.590199  0.031823
2000-01-06  0.299193  0.063820  0.095248
2000-01-07  1.292705 -1.033328  1.932373
2000-01-08  0.486099 -0.306094  0.242454


In [43]:
 #Attributes : Pandas has number of attributes allowing access to meta data
 #--> Series:index
# -->DataFrame:rows and columns
#shape
#values

In [11]:
#obtain all values as a np array
print(df.values)

[[ 0.41329763 -0.48187287  0.89829897]
 [-0.82670543  0.88051754 -0.17739496]
 [ 0.64787953  1.06121711  0.45710988]
 [-0.59253232  1.70330721 -1.03187445]
 [-0.12606454 -0.59019898  0.03182348]
 [ 0.29919254  0.06382029  0.09524753]
 [ 1.29270459 -1.03332821  1.93237326]
 [ 0.48609943 -0.30609411  0.24245387]]


In [18]:
#access rowa
print(df[:4])

                   A         B         C
2000-01-01  0.413298 -0.481873  0.898299
2000-01-02 -0.826705  0.880518 -0.177395
2000-01-03  0.647880  1.061217  0.457110
2000-01-04 -0.592532  1.703307 -1.031874


In [21]:
# work with columns
df.columns = [y.lower() for y in df.columns]
print(df.head(3))

                   a         b         c
2000-01-01  0.413298 -0.481873  0.898299
2000-01-02 -0.826705  0.880518 -0.177395
2000-01-03  0.647880  1.061217  0.457110


In [ ]:
 #Flexible Binary Operations

In [ ]:
# Matching/broadcasting behavoir

In [28]:
df = pd.DataFrame({'one' : pd.Series(np.random.randn(3), index=['a', 'b', 'c']),
                       'two' : pd.Series(np.random.randn(4), index=['a', 'b', 'c', 'd']),
                      'three' : pd.Series(np.random.randn(3), index=['b', 'c', 'd']
                                         )})
print(df)

        one     three       two
a  0.951734       NaN  0.771679
b  0.622141  0.793182 -0.101435
c -0.276947  1.380366 -0.212782
d       NaN -0.335020 -2.678583


In [29]:
row = df.iloc[1]
column = df['two']
print(row)
print(column)

one      0.622141
three    0.793182
two     -0.101435
Name: b, dtype: float64
a    0.771679
b   -0.101435
c   -0.212782
d   -2.678583
Name: two, dtype: float64


In [35]:
# add along the colums
df.add(row,axis=1)

one     three       two
a  1.573876       NaN  0.670243
b  1.244283  1.586365 -0.202870
c  0.345194  2.173549 -0.314217
d       NaN  0.458163 -2.780018

In [40]:
# add along the rows
df.add(column,axis=0)

one     three       two
a  1.723413       NaN  1.543357
b  0.520706  0.691747 -0.202870
c -0.489730  1.167584 -0.425565
d       NaN -3.013603 -5.357167

In [49]:
# Series have divmod operation builtin
s = pd.Series(np.arange(10))
div , rem = divmod(s,4)
print(div,rem)

0    0
1    0
2    0
3    0
4    1
5    1
6    1
7    1
8    2
9    2
dtype: int64 0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
8    0
9    1
dtype: int64


In [51]:
# divmod can also be done elementwise
div, rem = divmod(s, [2, 2, 3, 3, 4, 4, 5, 5, 6, 6])
print(div,rem)

0    0
1    0
2    0
3    1
4    1
5    1
6    1
7    1
8    1
9    1
dtype: int64 0    0
1    1
2    2
3    0
4    0
5    1
6    1
7    2
8    2
9    3
dtype: int64


In [52]:
# Boolean Indexing
#The operators are: | for or, & for and, and ~ for not
s = pd.Series(range(-3, 4))
s

0   -3
1   -2
2   -1
3    0
4    1
5    2
6    3
dtype: int64

In [53]:
# s where elements of s are greater than 2
s[s>2]

6    3
dtype: int64

In [54]:
s[s==2]

5    2
dtype: int64

In [58]:
s[(s>0) & (~(s == 1))]

5    2
6    3
dtype: int64

In [61]:
df[df['one']>0]

one     three       two
a  0.951734       NaN  0.771679
b  0.622141  0.793182 -0.101435